// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzapjsoviyvdrwwrolle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6YXBqc292aXl2ZHJ3d3JvbGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODUxMTIsImV4cCI6MjA2OTU2MTExMn0.J5etmFIorxVXVylLaj03ojeazYOXDbGhGfImguZ1HV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});